### ISSUE TITLE
cant import project

### ISSUE THREAD

**Issue by ismaiI1** [jiang111/CProgressButton#1]
I add root build.gradle  `maven { url 'https://jitpack.io' }` but getting error:  "failed to `resolve : compile 'com.github.jiang111:CProgressButton:1.2.7' `"

how can i import my project?

**Comment by jiang111** [comment]
com.github.jiang111:CProgressButton:v1.2.7     (version: v1.2.7)

**Comment by ismaiI1** [comment]
Thanks.
